version: "3.8"

services:
  ################################################################################
  # ROUTER SERVICES
  router-publisher:
    container_name: router-publisher
    depends_on:
      - rabbitmq
      - signer
      - redis
    image: ghcr.io/connext/router-publisher:$ROUTER_VERSION
    restart: always
    ports:
      - "8880:8080"
    # environment:
    #   - NXTP_CONFIG_FILE=/home/node/router/config.json
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    healthcheck:
      test: netstat -ltn | grep -c 8080
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./config.json:/home/node/packages/agents/router/config.json
    networks:
      - nxtp

  router-subscriber:
    container_name: router-subscriber
    depends_on:
      - rabbitmq
      - signer
      - redis
    image: ghcr.io/connext/router-subscriber:$ROUTER_VERSION
    restart: always
    ports:
      - "8881:8080"
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ./config.json:/home/node/packages/agents/router/config.json
    networks:
      - nxtp

  router-executor:
    container_name: router-executor
    depends_on:
      - rabbitmq
      - signer
      - redis
    image: ghcr.io/connext/router-executor:$ROUTER_VERSION
    restart: always
    ports:
      - "8882:8080"
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    volumes:
      - ./config.json:/home/node/packages/agents/router/config.json
    networks:
      - nxtp

  ################################################################################
  # AUXILIARY SERVICES
  signer:
    container_name: signer
    image: "consensys/web3signer:$WEB3SIGNER_VERSION"
    command: "--config-file=/home/node/signer/config.yaml eth1"
    restart: always
    volumes:
      - ./data/signerConfig/config.yaml:/home/node/signer/config.yaml
      - ./key.yaml:/home/node/signer/keyFiles/key.yaml
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    healthcheck:
      test: netstat -ltn | grep -c 9000
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nxtp

  ################################################################################
  # MONITORING SERVICES

  redis:
    container_name: redis
    image: "redis:$REDIS_VERSION"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  ################################################################################

  logdna:
    container_name: logdna
    image: logdna/logspout:$LOGDNA_VERSION
    restart: always
    environment:
      LOGDNA_KEY: $LOGDNA_KEY
      TAGS: $LOGDNA_TAG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    healthcheck:
      test: netstat -ltn | grep -c 80
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  ################################################################################

  prometheus:
    container_name: prometheus
    image: prom/prometheus:$PROMETHEUS_VERSION
    restart: always
    ports:
      - $PROMETHEUS_EXTERNAL_PORT:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=45d
    volumes:
      - ./data/prometheusConfig/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheusConfig/alert.rules.host:/etc/prometheus/alert.rules.host
      - ./data/prometheusConfig/alert.rules.prod:/etc/prometheus/alert.rules.prod
      - prometheus:/prometheus
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: netstat -ltn | grep -c 9090
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp


  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:$ALERTAMANGER_VERSION
    restart: always
    ports:
      - $ALERTMANAGER_EXTERNAL_PORT:9093
    command: --config.file=/config/alertmanager.yml --log.level=debug
    volumes:
      - ./data/alertmanagerConfig/alertmanager.yml:/config/alertmanager.yml
      - alertmanager:/data
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: netstat -ltn | grep -c 9093
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp


  grafana:
    container_name: grafana
    image: grafana/grafana:$GRAFANA_VERSION
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/grafanaConfig/grafana:/etc/grafana
      - ./data/grafanaConfig/dashboards:/etc/dashboards
      - grafana:/var/lib/grafana
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: netstat -ltn | grep -c 3000
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  loki:
    container_name: loki
    image: grafana/loki:$LOKI_VERSION
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./data/lokiConfig:/etc/loki
      - loki:/loki
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: netstat -ltn | grep -c 3100
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  promtail:
    container_name: promtail
    image: grafana/promtail:$PROMTAIL_VERSION
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./data/promtailConfig/config.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: exit 0
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  ################################################################################

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:$NODE_EXPORTER_VERSION
    restart: always
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns)(/)
    cap_add:
      - SYS_TIME
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: netstat -ltn | grep -c 9100
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:$CADVISOR_VERSION
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    logging:
      driver: json-file
      options:
        max-size: 10m
    healthcheck:
      test: netstat -ltn | grep -c 8080
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nxtp

################################################################################

networks:
  nxtp:

volumes:
  prometheus:
  grafana:
  loki:
  redis_data:
  alertmanager:
